name: Windows

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: cmd
      run: choco install cmake python ninja nasm yasm mingw llvm

    - name: Test
      shell: cmd
      run: test_win.bat
